version: '3.5'

services:
  trello:
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db_auth:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10
    build:
      context: .
      dockerfile: /src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    networks:
      - some-net
    depends_on:
      - db_auth
  db_auth:
#    container_name: db_auth2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image: postgres:15.2-alpine
#    restart: always
    networks:
      - some-net
networks:
  some-net:
    driver: bridge
#    volumes:
#      - ./src/main/resources/db/dev-data.sql:/docker-entrypoint-initdb.d/create_tables.sql